
services:
  engel.api.controllser.base:
    abstract: true
    class: Engel\Bundle\AppBundle\Controller\Api\BaseApiController
    arguments: [ @fos_rest.view_handler ]
    calls:
      - [ setDoctrine, [ @doctrine ]]


  engel.api.controller.shifts:
    class: Engel\Bundle\AppBundle\Controller\Api\ShiftsController
    parent: engel.api.controllser.base
    calls:
      - [ setContainer, [ @service_container ] ]

  engel.api.controller.locations:
    class: Engel\Bundle\AppBundle\Controller\Api\LocationsController
    parent: engel.api.controllser.base
    calls:
      - [ setContainer, [ @service_container ] ]
